/*
 * Loan Calculator
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"encoding/json"
	"io/ioutil"
	"net/http"
	// "fmt"
)

func CalcInterestOnly(calcLoan CalculateloanBody) (loanRep LoanRepayments) {
	//Declaring variables to be used for the home loan calculations - taken out of the CalculateloanBody struct
	principal := calcLoan.LoanAmount
	interest := float64(calcLoan.InterestRate)
	nYears := calcLoan.LoanTerm

	//Calculating the different parameters for loan repayments - taken out of the LoanRepayments struct
	//loanRep.MonthlyRepayments = principal * (interest / 12)
	loanRep.TotalInterestPayable = int32(float64(principal) * (interest / 12) * float64(nYears) * 12)

	//var i int32 //if we don't do this we can't use nYears since it is an int32
	if calcLoan.LoanType == "interest" {
	//creating the struct for
	for i := int32(0); i < nYears; i++ {
		var loanRepaymentsAmountOwing LoanRepaymentsAmountOwing
		loanRepaymentsAmountOwing.Principal = int32(principal)
		loanRepaymentsAmountOwing.Year = int32(i)
		loanRep.MonthlyRepayments = int32(float64(loanRepaymentsAmountOwing.Principal) * (interest / 12))
		loanRep.TotalInterestPayable = int32(float64(principal) * (interest / 12) * float64(nYears) * 12)
		loanRepaymentsAmountOwing.Interest = (loanRep.TotalInterestPayable - (loanRep.MonthlyRepayments * i))
		loanRepaymentsAmountOwing.Total = loanRepaymentsAmountOwing.Principal + loanRepaymentsAmountOwing.Interest
		loanRep.AmountOwing = append(loanRep.AmountOwing, loanRepaymentsAmountOwing)
	}
	}

	return loanRep
}

func CalculateLoan(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	// j,_:=json.Marshal("hello")

	//     w.Write(j)

	requestBodyBytes, _ := ioutil.ReadAll(r.Body)
	var newPerson CalculateloanBody
	json.Unmarshal(requestBodyBytes, &newPerson) //

	var res LoanRepayments
	res = CalcInterestOnly(newPerson)

	

	jresponse, _ := json.Marshal(&res) //convert CalculateloanBody type to string for sending back

	w.Write(jresponse)

}
